name: RetainML CI - Train Churn Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create models directory
        run: mkdir -p models

      - name: Train churn model
        run: |
          python src/train.py
          echo "Contents of models directory:"
          ls -la models

      - name: Show training metrics
        run: cat models/metrics.json

      - name: Upload trained model and metrics
        uses: actions/upload-artifact@v4
        with:
          name: retainml-model-${{ github.run_id }}
          path: models/
